### PR TITLE
FLUID-6250: reverting package-lock.json for dev workflow

### PR DESCRIPTION
**Pull request by atisayajain**
Fixes issue: https://issues.fluidproject.org/browse/FLUID-6250

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
I have tested this both with a `--test` release and with a dev release, it addresses the problem reported.

**Comment by jobara** [comment]
@atisayajain could you please send me a signed [Contributor License Agreement](https://wiki.fluidproject.org/download/attachments/1707690/FluidCLA_V3.0.pdf?version=1&modificationDate=1289324277000&api=v2). You can read more info about it at https://wiki.fluidproject.org/display/fluid/Fluid+Licensing

**Comment by atisayajain** [comment]
@jobara Please find the signed agreement [here](https://drive.google.com/open?id=1y8QpYJn5PIZZzNXeQXH-QrWHDDOMwtzs).

Is this okay or should I email it to you?

**Comment by jobara** [comment]
@atisayajain thanks I got your CLA. You can delete the link if you'd prefer not to keep it public.

**Comment by atisayajain** [comment]
@jobara thanks for confirmation. Anything else I need to do specific to this PR?

Also, I was thinking about adding code of conduct and contributing guidelines to this repo. Can I submit a new PR for it? Or should I open an issue on JIRA first?

**Comment by jobara** [comment]
@atisayajain thanks. Best to file a JIRA about it first and then submit a PR against that JIRA.

**Comment by jobara** [comment]
@atisayajain could you please update the e.g in the [comment](https://github.com/fluid-project/fluid-publish/blob/master/publish.js#L266) and also the README entry for the [cleanCMD](https://github.com/fluid-project/fluid-publish/blob/master/README.md#options-1). It seems that even the what's in master is out of date. If there are other areas where the command is used that needs to be updated, please fix those as well.

Lastly, please bump the version number in the package.json file to 2.0.1

**Comment by atisayajain** [comment]
@jobara I have made the changes as you asked. Couldn't find the use of command elsewhere. Still please let me know if I missed something somewhere.

Please let me know if any other changes need to be made.

**Comment by the-t-in-rtf** [comment]
Hi, @atisayajain, the close step is usually reserved for pulls that won't be merged, I assume you still want this to be reviewed and merged?

**Comment by jobara** [comment]
Hi @the-t-in-rtf, @atisayajain, accidentally closed this PR when he was trying to clean up a commit. He has opened a new PR to replace this one. https://github.com/fluid-project/fluid-publish/pull/10

**Comment by the-t-in-rtf** [comment]
Thanks for the explanation, @jobara, glad the work is still ongoing.  I'll follow the new ticket.

**Pull request closed without merging**
